### ISSUE TITLE
Issue installing fastscape 

### ISSUE THREAD

**Issue by camersiegNCSU** [fastscape-lem/fastscape#27]
Hello,

I am trying to start running models with fast scape however when I import fastscape I get a module not found error for the "channel" process file. "fastscapelib_fortran doesn't seem to be recognized. Any help would be appreciated.
![image](https://user-images.githubusercontent.com/125084381/236277886-28e4dcd8-2210-4a04-aa8e-c804b8ac878e.png)

**Comment by benbovy** [comment]
Hi @camersiegNCSU,

How did you installed fastscape? 

This package depends on https://github.com/fastscape-lem/fastscapelib-fortran, for which Python binary wheels are not available on pypi.org. You either to install the Python bindings from source or (strongly recommended!) installed the pre-compiled Python extension using conda:

```
conda install fastscapelib-f2py -c conda-forge
```

More info in the documentation: https://fastscape.readthedocs.io/en/latest/install.html

**Comment by benbovy** [comment]
I'm closing this issue since it should be solved with instructions in my last comment. Feel free to re-open it if the issue persists.
