### ISSUE TITLE
numpy.int in flow.py

### ISSUE THREAD

**Issue by jeanbraun** [fastscape-lem/fastscape#30]
Hello @benbovy. I have encountered an issue with fastscape where it complains about a depreciated numpy integer type on line 93 of flow.py. I believe np.int should be replaced by int as done everywhere else in the process. I managed to solve it by downgrading the version of numpy and xarray I use to 1.23.5 and 2022.3.0 but I am not sure if this is what fixed the problem. I hope this helps. Jean

**Comment by benbovy** [comment]
Thanks for the report @jeanbraun (sorry for the wait I've just noticed this issue). Fixed in e259493f4dca42675c29ff8c5a061f4d356b002c
